services:
  api:
    container_name: table-service-api
    restart: unless-stopped
    build:
      context: ./backend
    expose:
      - "8000"
    ports:
      - "8004:8000"

  nginx:
    container_name: table-service-nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "8003:80"
    depends_on:
      - api

  redis:
    image: redis:7.2-alpine
    container_name: table-service-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my_secure_password_123
    command: >
      redis-server 
      --requirepass $${REDIS_PASSWORD}  
      --appendonly yes                  
      --appendfsync everysec            
      --save 60 1000                    
      --maxmemory 512mb                 
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local