# Generated by Django 5.2.4 on 2025-09-23 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 23, 1, 37, 48, 735142), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 1, 37, 48, 735127)),
        ),
    ]
