# Generated by Django 4.2.23 on 2025-10-17 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_edit_at_alter_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 17, 16, 10, 16, 565189), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 16, 10, 16, 565162)),
        ),
    ]
