# Generated by Django 4.2.23 on 2025-10-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_edit_at_alter_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 20, 18, 18, 57, 810486), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 18, 57, 810473)),
        ),
    ]
