# Generated by Django 4.2.23 on 2025-11-05 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_edit_at_alter_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 5, 11, 11, 25, 798985), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 11, 11, 25, 798968)),
        ),
    ]
