# Generated by Django 4.2.23 on 2025-11-05 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_edit_at_alter_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 5, 15, 27, 46, 471602), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 15, 27, 46, 471588)),
        ),
    ]
