# Generated by Django 5.2.3 on 2025-06-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_column_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата')], default='text', max_length=10),
        ),
    ]
