# Generated by Django 5.2.3 on 2025-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_column_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='value',
        ),
        migrations.AddField(
            model_name='cell',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='integer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
