# Generated by Django 5.2.3 on 2025-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_remove_cell_value_cell_boolean_value_cell_date_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='date_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
