# Generated by Django 5.2.3 on 2025-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_cell_date_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
    ]
