# Generated by Django 5.2.3 on 2025-07-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_alter_employee_id_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_parent', models.IntegerField(blank=True, null=True)),
                ('id_filial', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, null=True)),
                ('set_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='setdate',
            new_name='set_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tabnum',
            new_name='tabnumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gesch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_post',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_poststaff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='kostl',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='code',
        ),
        migrations.AddField(
            model_name='employee',
            name='post_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='boss',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='long_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='set_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='short_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filial',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RowFilialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_permissions', to='tables.row')),
            ],
            options={
                'unique_together': {('row', 'filial')},
            },
        ),
    ]
