# Generated by Django 5.2.3 on 2025-07-01 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_department_rename_enddate_employee_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RowLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='tables.row')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
