# Generated by Django 5.2.3 on 2025-07-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_alter_rowlock_locked_at_tablepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFilialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_permissions', to='tables.table')),
            ],
            options={
                'unique_together': {('table', 'filial')},
            },
        ),
    ]
