# Generated by Django 5.2.3 on 2025-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_tablefilialpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowlock',
            name='locked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
