# Generated by Django 5.2.3 on 2025-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_alter_rowlock_locked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='rowlock',
            name='locked_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
