# Generated by Django 5.2.3 on 2025-07-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_tablefiliallock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefiliallock',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='tablefiliallock',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_add_permissions', to='tables.table'),
        ),
    ]
