# Generated by Django 5.2.3 on 2025-07-07 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_admin_delete_tableadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Если отмечено, поле должно быть заполнено при создании/редактировании строки', verbose_name='Обязательное поле'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 14, 24, 13, 526058)),
        ),
    ]
