# Generated by Django 5.2.4 on 2025-08-07 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_admin_delete_tableadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 14, 8, 46, 741966)),
        ),
    ]
