# Generated by Django 5.2.3 on 2025-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Логическое'), ('date', 'Дата')], default='text', max_length=10),
        ),
    ]
