# Generated by Django 5.2.3 on 2025-06-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_cell_date_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowpermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rowpermission',
            name='created_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tables.row'),
        ),
    ]
