# Generated by Django 5.2.3 on 2025-06-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_row_created_by_rowpermission_can_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowpermission',
            name='created_by_owner',
        ),
    ]
