# Generated by Django 5.2.3 on 2025-07-03 13:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_remove_tablefiliallock_is_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 7, 3, 13, 29, 6, 349558))),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='tables.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор таблицы',
                'verbose_name_plural': 'Администраторы таблиц',
                'unique_together': {('table', 'user')},
            },
        ),
    ]
