# Generated by Django 5.2.4 on 2025-08-18 10:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_alter_admin_created_at_alter_department_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 10, 7, 40, 955812)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 10, 7, 40, 955696)),
        ),
        migrations.CreateModel(
            name='CellLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_lock_cell', to='tables.cell', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_lock_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
