# Generated by Django 5.2.4 on 2025-08-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_alter_admin_created_at_alter_table_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 10, 27, 50, 998765)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 10, 27, 50, 997225)),
        ),
    ]
