# Generated by Django 4.2.23 on 2025-08-27 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_alter_admin_created_at_alter_table_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='integer_value',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='text_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='boolean_value',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='float_value',
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 10, 33, 39, 405500)),
        ),
        migrations.AlterField(
            model_name='cell',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 10, 33, 39, 407745)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 10, 33, 39, 405279)),
        ),
    ]
