# Generated by Django 4.2.23 on 2025-09-01 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_rename_integer_value_cell_table_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 10, 38, 55, 490280)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 10, 38, 55, 492993)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 10, 38, 55, 489967)),
        ),
    ]
