# Generated by Django 4.2.23 on 2025-09-02 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0026_tablepermission_can_edit_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 11, 29, 27, 89557)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 11, 29, 27, 92259)),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='filial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 11, 29, 27, 89341)),
        ),
        migrations.CreateModel(
            name='ColumnPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tables.column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('column', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ColumnFilialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delete', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_add_permissions', to='tables.column')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
            ],
            options={
                'unique_together': {('column', 'filial')},
            },
        ),
    ]
