# Generated by Django 5.2.4 on 2025-09-23 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_alter_admin_created_at_alter_celllock_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 0, 27, 20, 209059)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 0, 27, 20, 210789)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 0, 27, 20, 207325)),
        ),
    ]
