# Generated by Django 4.2.23 on 2025-09-30 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0032_alter_admin_created_at_alter_celllock_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 30, 9, 41, 20, 661695)
            ),
        ),
        migrations.AlterField(
            model_name="celllock",
            name="locked_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 30, 9, 41, 20, 664487)
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("integer", "Целое число"),
                    ("float", "Число с плавающей точкой"),
                    ("boolean", "Логическое"),
                    ("date", "Дата"),
                    ("select", "Выпадающий список"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 30, 9, 41, 20, 661498)
            ),
        ),
        migrations.CreateModel(
            name="SelectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("column_id", "name")},
            },
        ),
    ]
