# Generated by Django 4.2.23 on 2025-10-17 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0033_alter_admin_created_at_alter_celllock_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 17, 16, 30, 46, 229502)
            ),
        ),
        migrations.AlterField(
            model_name="celllock",
            name="locked_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 17, 16, 30, 46, 232365)
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("integer", "Целое число"),
                    ("float", "Число с плавающей точкой"),
                    ("boolean", "Логическое"),
                    ("date", "Дата"),
                    ("select", "Выпадающий список"),
                    ("auto", "Автоинкремент"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 17, 16, 30, 46, 229300)
            ),
        ),
    ]
