# Generated by Django 4.2.23 on 2025-10-20 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0033_table_with_cell_confirm_table_with_cell_logging_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('old_value', models.CharField()),
                ('new_value', models.CharField()),
                ('cell_id', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 13, 27, 753463)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 13, 27, 756270)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 13, 27, 753234)),
        ),
    ]
