# Generated by Django 4.2.23 on 2025-10-21 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0034_alter_admin_created_at_alter_celllock_locked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="related_column_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 21, 11, 11, 8, 251837)
            ),
        ),
        migrations.AlterField(
            model_name="celllock",
            name="locked_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 21, 11, 11, 8, 254758)
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 21, 11, 11, 8, 251606)
            ),
        ),
    ]
