# Generated by Django 4.2.23 on 2025-10-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0034_celleditlog_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 18, 57, 806744)),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='cell_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 18, 57, 809587)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 18, 57, 806526)),
        ),
    ]
