# Generated by Django 4.2.23 on 2025-10-20 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_alter_admin_created_at_alter_celleditlog_cell_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 30, 41, 569471)),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='new_value',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='old_value',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 30, 41, 572179)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 18, 30, 41, 569230)),
        ),
    ]
