# Generated by Django 4.2.23 on 2025-10-21 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0036_alter_admin_created_at_alter_celleditlog_new_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celleditlog',
            name='row_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 11, 30, 33, 841218)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 11, 30, 33, 844065)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 21, 11, 30, 33, 840997)),
        ),
    ]
