# Generated by Django 4.2.23 on 2025-10-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_column_related_column_ids_alter_admin_created_at_and_more'),
        ('tables', '0037_celleditlog_row_id_alter_admin_created_at_and_more'),
    ]

    operations = [
    ]
