# Generated by Django 4.2.23 on 2025-10-30 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0038_merge_20251030_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnpermission',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 12, 1, 171037)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 12, 1, 174115)),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 12, 1, 170794)),
        ),
    ]
