# Generated by Django 4.2.23 on 2025-10-30 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0039_columnpermission_table_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 18, 11, 443989)),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 18, 11, 446881)),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='table',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 9, 18, 11, 443766)),
        ),
    ]
