# Generated by Django 5.2.4 on 2025-11-30 16:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0042_alter_admin_created_at_alter_celllock_locked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name': 'Ячейка', 'verbose_name_plural': 'Ячейки'},
        ),
        migrations.AlterModelOptions(
            name='celleditlog',
            options={'verbose_name': 'Лог изменения ячейки', 'verbose_name_plural': 'Лог изменений ячеек'},
        ),
        migrations.AlterModelOptions(
            name='celllock',
            options={'verbose_name': 'Блокировка ячейки', 'verbose_name_plural': 'Блокировки ячеек'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order'], 'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AlterModelOptions(
            name='columnfilialpermission',
            options={'verbose_name': 'Право филиала на колонку', 'verbose_name_plural': 'Права филиалов на колонки'},
        ),
        migrations.AlterModelOptions(
            name='columnpermission',
            options={'verbose_name': 'Право доступа к колонке', 'verbose_name_plural': 'Права доступа к колонкам'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['order'], 'verbose_name': 'Строка', 'verbose_name_plural': 'Строки'},
        ),
        migrations.AlterModelOptions(
            name='rowfilialpermission',
            options={'verbose_name': 'Право филиала на строку', 'verbose_name_plural': 'Права филиалов на строки'},
        ),
        migrations.AlterModelOptions(
            name='rowlock',
            options={'verbose_name': 'Блокировка строки', 'verbose_name_plural': 'Блокировки строк'},
        ),
        migrations.AlterModelOptions(
            name='rowpermission',
            options={'verbose_name': 'Право доступа к строке', 'verbose_name_plural': 'Права доступа к строкам'},
        ),
        migrations.AlterModelOptions(
            name='selecttype',
            options={'verbose_name': 'Значение выпадающего списка', 'verbose_name_plural': 'Значения выпадающих списков'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
        migrations.AlterModelOptions(
            name='tablefiliallock',
            options={'verbose_name': 'Блокировка филиала', 'verbose_name_plural': 'Блокировки филиалов'},
        ),
        migrations.AlterModelOptions(
            name='tablefilialpermission',
            options={'verbose_name': 'Право доступа филиала', 'verbose_name_plural': 'Права доступа филиалов'},
        ),
        migrations.AlterModelOptions(
            name='tablepermission',
            options={'verbose_name': 'Право доступа к таблице', 'verbose_name_plural': 'Права доступа к таблицам'},
        ),
        migrations.AlterModelOptions(
            name='tableuseronline',
            options={'verbose_name': 'Пользователь онлайн', 'verbose_name_plural': 'Пользователи онлайн'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 44, 11, 207157), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='column',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID колонки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='formula_value',
            field=models.TextField(blank=True, null=True, verbose_name='Значение формулы'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID строки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='table_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID таблицы'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='cell_id',
            field=models.IntegerField(verbose_name='ID ячейки'),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='new_value',
            field=models.CharField(null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='old_value',
            field=models.CharField(null=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='row_id',
            field=models.IntegerField(null=True, verbose_name='ID строки'),
        ),
        migrations.AlterField(
            model_name='celleditlog',
            name='user_id',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_lock_cell', to='tables.cell', unique=True, verbose_name='Ячейка'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 44, 11, 208633), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_lock_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('select', 'Выпадающий список'), ('auto', 'Автоинкремент')], default='text', max_length=10, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название колонки'),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='related_column_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Связанные колонки'),
        ),
        migrations.AlterField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='columnfilialpermission',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Может удалять'),
        ),
        migrations.AlterField(
            model_name='columnfilialpermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Может редактировать'),
        ),
        migrations.AlterField(
            model_name='columnfilialpermission',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_add_permissions', to='tables.column', verbose_name='Колонка'),
        ),
        migrations.AlterField(
            model_name='columnfilialpermission',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Может редактировать'),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Может просматривать'),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='column',
            field=models.IntegerField(verbose_name='ID колонки'),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='table',
            field=models.IntegerField(verbose_name='ID таблицы'),
        ),
        migrations.AlterField(
            model_name='columnpermission',
            name='user',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='department',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id_filial',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID филиала'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id_parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID родительского отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='long_name',
            field=models.CharField(blank=True, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='set_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, null=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_department',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID отдела'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_filial',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID филиала'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_name',
            field=models.CharField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='secondname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='set_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tabnumber',
            field=models.IntegerField(unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='boss',
            field=models.CharField(blank=True, null=True, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='long_name',
            field=models.CharField(blank=True, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='set_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='short_name',
            field=models.CharField(blank=True, null=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='tables.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='row',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rows', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='row',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='row',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Может удалять'),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Может редактировать'),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='filial',
            field=models.IntegerField(verbose_name='ID филиала'),
        ),
        migrations.AlterField(
            model_name='rowfilialpermission',
            name='row',
            field=models.IntegerField(verbose_name='ID строки'),
        ),
        migrations.AlterField(
            model_name='rowlock',
            name='locked_at',
            field=models.DateTimeField(verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='rowlock',
            name='row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='tables.row', verbose_name='Строка'),
        ),
        migrations.AlterField(
            model_name='rowlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_locks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Может удалять'),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Может редактировать'),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='row',
            field=models.IntegerField(verbose_name='ID строки'),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='table',
            field=models.IntegerField(verbose_name='ID таблицы'),
        ),
        migrations.AlterField(
            model_name='rowpermission',
            name='user',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='selecttype',
            name='column_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID колонки'),
        ),
        migrations.AlterField(
            model_name='selecttype',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 44, 11, 207010), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='table',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название таблицы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='with_cell_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждение ячеек'),
        ),
        migrations.AlterField(
            model_name='table',
            name='with_cell_logging',
            field=models.BooleanField(default=False, verbose_name='Логирование изменений'),
        ),
        migrations.AlterField(
            model_name='tablefiliallock',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='tablefiliallock',
            name='locked_at',
            field=models.DateTimeField(verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='tablefiliallock',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заблокировал'),
        ),
        migrations.AlterField(
            model_name='tablefiliallock',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_add_permissions', to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='tablefilialpermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Может просматривать'),
        ),
        migrations.AlterField(
            model_name='tablefilialpermission',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='tablefilialpermission',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_permissions', to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Может редактировать'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Может просматривать'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tableuseronline',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='tableuseronline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
