# Generated by Django 5.2.4 on 2025-11-30 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0043_alter_cell_options_alter_celleditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 47, 30, 210327), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 47, 30, 211987), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 47, 30, 210197), verbose_name='Дата создания'),
        ),
    ]
