# Generated by Django 5.2.4 on 2025-11-30 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0044_alter_admin_created_at_alter_celllock_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 48, 43, 835821), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 48, 43, 837207), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 48, 43, 835678), verbose_name='Дата создания'),
        ),
    ]
