# Generated by Django 5.2.4 on 2025-11-30 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0045_alter_admin_created_at_alter_celllock_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='related_number_column_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Связанная колонка с датой'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 18, 5, 50, 815737), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 18, 5, 50, 816953), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 18, 5, 50, 815519), verbose_name='Дата создания'),
        ),
    ]
