# Generated by Django 5.2.4 on 2025-11-30 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0046_column_related_number_column_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='default_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 21, 12, 198291), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 21, 12, 199655), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 21, 12, 198172), verbose_name='Дата создания'),
        ),
    ]
