# Generated by Django 5.2.4 on 2025-11-30 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0047_column_default_value_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 37, 54, 257272), verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='celllock',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 37, 54, 258548), verbose_name='Время блокировки'),
        ),
        migrations.AlterField(
            model_name='column',
            name='default_value',
            field=models.CharField(blank=True, null=True, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 20, 37, 54, 257059), verbose_name='Дата создания'),
        ),
    ]
